### PR TITLE
Ccdb api bug fixes

### PR DESCRIPTION
**Pull request by cfarm**
Copy + CSS + JS bug fixes for the CCDB api docs
## Additions
- cf-expandables css + js
- cf-icons + cf-typography css for the PDF icons on index page
- font files for the icons
- cf-tables css for the field reference table styling on small screens
## Removals
- outdated expandables js + css
## Changes
- changed "Release data" to "Release notes" in nav, filename, page title
- updated HTML for the Release notes expandables - lots o copy n paste so some extra eyes on this to make sure the content matches the previous version would be great.
## Testing

I tested the expandables in ie8 and they work unlike the previous version

to test my branch locally:
- clone my repo to your local Sites folder: `git clone git@github.com:cfarm/api-1.git`
- check out this branch: `git checkout ccdb-bug-fixes`
- run it locally: `bundle exec jekyll serve --watch --baseurl ''`
- view in browser: [http://localhost:4000/ccdb/](http://localhost:4000/ccdb/)
- compare to previous version here, especially release notes copy: http://cfarm.github.io/api-1/ccdb/data.html
## Review
- @huetingj - check release notes content + all copy + icons
- @vczosek - code review
## Screenshots

screen shot 2016-01-13 at 1 40 31 pm

screen shot 2016-01-13 at 1 40 57 pm
screen shot 2016-01-13 at 1 41 06 pm
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [ ] New functions include new tests
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by cfarm** [comment]
Note: this is only a PR in my fork for now, I'll be creating a PR w the updates that add this project documentation to the [cfpb/api](https://github.com/cfpb/api) site for release later this week.

**Comment by cfarm** [comment]
@huetingj you can check out the updated pages here now: http://cfarm.github.io/api-1/ccdb/data.html

I did a diff in Sublime of the release notes text before/after and it's identical so no need to comb over that after all. Yay techmological automotation!

**Comment by jenn-franklin** [comment]
Looks good to me!

**Comment by virginiacc** [comment]
@cfarm Looks good to me too! One thing I was wondering is if we'd want to look at managing the dependencies if we were bringing in more CF components, but I think this is fine now. :+1:

**Pull request merged**
